### ISSUE TITLE
[Bug]: Open Graph image is not available

### ISSUE THREAD

**Issue by theritikchoure** [proudparrot2/artclass#11]
### Description

Below og tag is used for open graph image

```
 <meta content="icon.png" property="og:image" />
```

Relative path doesn't work for open graph tags, you should have to use absolute url.

![image](https://user-images.githubusercontent.com/56495602/236464709-7cbd8649-b0ff-434d-83cb-efb68bff1ba2.png)

**Comment by proudparrot2** [comment]
Alright, thanks!
I’ll update that when I can
